spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///video_db?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: 
    password: 
    hikari:
      connection-test-query: SELECT 1
      pool-name: HikariPool
      auto-commit: true
      idle-timeout: 60000
      connection-timeout: 60000
      max-lifetime: 0
      minimum-idle: 10
      maximum-pool-size: 10
  redis:
    host: 
    port: 6391
    database: 3
    timeout: 1800000
    password: 
    lettuce:
      pool:
        max-active: 20
        max-wait: 1
        max-idle: 5
        min-idle: 0
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: top/yangbuyi/service_user/mapper/xml/*.xml

feign:
  sentinel:
    enabled: true

wx:
  open:
    app_id: 
    app_secret: 
    redirect_url: http://www.sphskla.cn/service_user/user/wx/callBack